const menuData = [
  { id: 1, name: "TEA", category: "Hot Beverages", price: 15 },
  { id: 2, name: "MILK", category: "Hot Beverages", price: 15 },
  { id: 3, name: "LEMON TEA", category: "Hot Beverages", price: 15 },
  { id: 4, name: "COFFEE", category: "Hot Beverages", price: 20 },
  { id: 5, name: "SPECIAL TEA", category: "Hot Beverages", price: 20 },
  { id: 6, name: "RAGI MALT", category: "Hot Beverages", price: 20 },
  { id: 7, name: "CHUKKU COFFEE", category: "Hot Beverages", price: 20 },
  { id: 8, name: "BOOST", category: "Hot Beverages", price: 20 },
  { id: 9, name: "HORLICKS", category: "Hot Beverages", price: 20 },

  { id: 10, name: "APPLE", category: "Fresh Juice", price: 90 },
  { id: 11, name: "ORANGE", category: "Fresh Juice", price: 90 },
  { id: 12, name: "GRAPE", category: "Fresh Juice", price: 50 },
  { id: 13, name: "CUSTARD APPLE", category: "Fresh Juice", price: 80 },
  { id: 14, name: "STRAWBERRY", category: "Fresh Juice", price: 90 },
  { id: 15, name: "KIWI", category: "Fresh Juice", price: 100 },
  { id: 16, name: "ATHI", category: "Fresh Juice", price: 90 },
  { id: 17, name: "PINEAPPLE", category: "Fresh Juice", price: 60 },
  { id: 18, name: "POMEGRANATE", category: "Fresh Juice", price: 90 },
  { id: 19, name: "MANGO", category: "Fresh Juice", price: 100 },
  { id: 20, name: "CARROT", category: "Fresh Juice", price: 80 },
  { id: 21, name: "BANANA", category: "Fresh Juice", price: 100 },
  { id: 22, name: "BEETROOT", category: "Fresh Juice", price: 100 },
  { id: 23, name: "BUTTER FRUIT", category: "Fresh Juice", price: 120 },
  { id: 24, name: "DRAGON FRUIT", category: "Fresh Juice", price: 80 },
  { id: 25, name: "CHIKKU", category: "Fresh Juice", price: 80 },
  { id: 26, name: "NONGU", category: "Fresh Juice", price: 30 },
  { id: 27, name: "TENDER COCONUT", category: "Fresh Juice", price: 80 },
  { id: 28, name: "LEMON", category: "Fresh Juice", price: 50 },
  { id: 29, name: "MOSAMBI", category: "Fresh Juice", price: 50 },
  { id: 30, name: "WATERMELON", category: "Fresh Juice", price: 40 },
  { id: 31, name: "MUSKMELON", category: "Fresh Juice", price: 120 },
  { id: 32, name: "NELLIKKA", category: "Fresh Juice", price: 35 },
  { id: 33, name: "ABC JUICE", category: "Fresh Juice", price: 40 },
  { id: 34, name: "LEMON SALT SODA", category: "Fresh Juice", price: 35 },
  { id: 35, name: "GUAVA", category: "Fresh Juice", price: 40 },
  { id: 36, name: "Royal Falooda", category: "Falooda Special", price: 140 },
  { id: 37, name: "King Falooda", category: "Falooda Special", price: 190 },
  { id: 38, name: "Choclate Falooda", category: "Falooda Special", price: 200 },
  { id: 39, name: "Fruit Punch Falooda", category: "Falooda Special", price: 120 },
  { id: 40, name: "Rubdi Falooda", category: "Falooda Special", price: 150 },
  { id: 41, name: "Mango Falooda", category: "Falooda Special", price: 150 },
  { id: 42, name: "Butter Scotch Falooda", category: "Falooda Special", price: 150 },
  { id: 43, name: "Pista Falooda", category: "Falooda Special", price: 150 },
  { id: 44, name: "Puttu Falooda", category: "Falooda Special", price: 250 },
  { id: 45, name: "Arabic Falooda", category: "Falooda Special", price: 150 },
  { id: 46, name: "Dry Fruit Falooda", category: "Falooda Special", price: 150 },
  { id: 47, name: "Falooda Split", category: "Falooda Special", price: 150 },
  { id: 48, name: "Normal Falooda", category: "Falooda Special", price: 150 },
  { id: 49, name: "KM Special Falooda", category: "Falooda Special", price: 250 },

  // Ice Cream & Desserts
  { id: 50, name: "Death by Choclate", category: "Ice Cream & Desserts", price: 150 },
  { id: 51, name: "Flurry Brownie", category: "Ice Cream & Desserts", price: 120 },
  { id: 52, name: "Sizzler Hot Brownie", category: "Ice Cream & Desserts", price: 180 },
  { id: 53, name: "4Sons", category: "Ice Cream & Desserts", price: 140 },
  { id: 54, name: "Nutella Sundea", category: "Ice Cream & Desserts", price: 160 },
  { id: 55, name: "Brownie Split", category: "Ice Cream & Desserts", price: 150 },
  { id: 56, name: "Faramis", category: "Ice Cream & Desserts", price: 150 },
  { id: 57, name: "Chocozilla", category: "Ice Cream & Desserts", price: 150 },
  { id: 58, name: "Perfite", category: "Ice Cream & Desserts", price: 150 },
  { id: 59, name: "Italina Delight", category: "Ice Cream & Desserts", price: 150 },
  { id: 60, name: "Dilkhush", category: "Ice Cream & Desserts", price: 130 },
  { id: 61, name: "Mango Falooda", category: "Ice Cream & Desserts", price: 150 },
  { id: 62, name: "Butter Scotch Choconut", category: "Ice Cream & Desserts", price: 250 },
  { id: 63, name: "Banana Split", category: "Ice Cream & Desserts", price: 110 },
  { id: 64, name: "Dry Fruit with Honey Icecream", category: "Ice Cream & Desserts", price: 200 },
  { id: 65, name: "American Sundae", category: "Ice Cream & Desserts", price: 200 },
  { id: 66, name: "Puttu Ice Cream", category: "Ice Cream & Desserts", price: 200 },

  // Chat
  { id: 67, name: "DAHI PURI CHAT", category: "Chat", price: 60 },
  { id: 68, name: "DAHI PAPDI CHAT", category: "Chat", price: 60 },
  { id: 69, name: "DAHI SAMOSA", category: "Chat", price: 60 },
  { id: 70, name: "SEV PURI", category: "Chat", price: 70 },
  { id: 71, name: "CHEESE SEV PURI", category: "Chat", price: 60 },
  { id: 72, name: "MAYONAISE PURI", category: "Chat", price: 60 },
  { id: 73, name: "BHEL PURI", category: "Chat", price: 60 },
  { id: 74, name: "CHEESE BHEL PURI", category: "Chat", price: 80 },
  { id: 75, name: "PANI PURI", category: "Chat", price: 30 },
  { id: 76, name: "CHANNA MASALA", category: "Chat", price: 50 },
  { id: 77, name: "SAMOSA CHANNA MASALA", category: "Chat", price: 60 },
  { id: 78, name: "MASALA PURI", category: "Chat", price: 60 },
  { id: 79, name: "PAV BHAJI", category: "Chat", price: 100 },
  { id: 80, name: "CHEESE PAV BHAJI", category: "Chat", price: 80 },
  { id: 81, name: "PANNER PAV BHAJI", category: "Chat", price: 70 },
  { id: 82, name: "MIXED CHAT", category: "Chat", price: 70 },

  // Snacks
  { id: 83, name: "SAMOSA", category: "Snacks", price: 15 },
  { id: 84, name: "PUFF", category: "Snacks", price: 15 },
  { id: 85, name: "VADA PAV", category: "Snacks", price: 30 },

  // Fries
  { id: 86, name: "FRENCH FRIES", category: "Fries", price: 70 },
  { id: 87, name: "PERI PERI FRIES", category: "Fries", price: 80 },
  { id: 88, name: "CHEESE FRIES", category: "Fries", price: 90 },
  { id: 89, name: "POTATO CHEESE SHOTS", category: "Fries", price: 80 },

  // Momos
  { id: 90, name: "VEG MOMOS", category: "Momos", price: 90 },
  { id: 91, name: "PANNER MOMOS", category: "Momos", price: 100 },

  // Mojito
  { id: 92, name: "Mojito", category: "Mojito", price: 70 },
  { id: 93, name: "Mint Mojito", category: "Mojito", price: 70 },
  { id: 94, name: "Lime Mojito", category: "Mojito", price: 70 },
  { id: 95, name: "Green Apple Mojito", category: "Mojito", price: 100 },
  { id: 96, name: "Guava Mojito", category: "Mojito", price: 100 },
  { id: 97, name: "Blue Berry Mojito", category: "Mojito", price: 100 },
  { id: 98, name: "Mango Mojito", category: "Mojito", price: 100 },
  { id: 99, name: "Black Currant Mojito", category: "Mojito", price: 100 },
  { id: 100, name: "Water Melon Punch Mojito", category: "Mojito", price: 100 },
  { id: 101, name: "Raspberry Mojito", category: "Mojito", price: 100 },
  { id: 102, name: "Mint Mojito", category: "Mojito", price: 40 },
  { id: 103, name: "Chilli Soda", category: "Mojito", price: 40 },
  { id: 104, name: "Mint Soda", category: "Mojito", price: 40 },
  { id: 105, name: "Pineapple Soda", category: "Mojito", price: 40 },
  { id: 106, name: "Orange Soda", category: "Mojito", price: 40 },
  { id: 107, name: "Number Soda", category: "Mojito", price: 40 },
  // Avil Milk
  { id: 108, name: "Regular", category: "Avil Milk", price: 60 },
  { id: 109, name: "Strawberry", category: "Avil Milk", price: 80 },
  { id: 110, name: "Butterscotch", category: "Avil Milk", price: 80 },
  { id: 111, name: "Pista", category: "Avil Milk", price: 80 },
  { id: 112, name: "Dry Nuts", category: "Avil Milk", price: 140 },
  { id: 113, name: "Boost", category: "Avil Milk", price: 70 },
  { id: 114, name: "Rose Milk", category: "Avil Milk", price: 70 },
  { id: 115, name: "Guava", category: "Avil Milk", price: 70 },
  { id: 116, name: "Mango", category: "Avil Milk", price: 70 },
  { id: 117, name: "Chocolate", category: "Avil Milk", price: 80 },
  { id: 118, name: "Kulfi", category: "Avil Milk", price: 150 },
  { id: 119, name: "KM Special Avil Milk", category: "Avil Milk", price: 150 },

  // Milkshake Special
  { id: 120, name: "Strawberry Punch with Chocolate", category: "Milkshake Special", price: 150 },
  { id: 121, name: "Alphonsa Mango with Chocolate", category: "Milkshake Special", price: 130 },
  { id: 122, name: "Mango Punch", category: "Milkshake Special", price: 150 },
  { id: 123, name: "SPL Grapes Galaxy Shake", category: "Milkshake Special", price: 150 },
  { id: 124, name: "Dragon Fruit Shake", category: "Milkshake Special", price: 100 },
  { id: 125, name: "Kiwi Fruit Shake", category: "Milkshake Special", price: 100 },
  { id: 126, name: "Blueberry Shake", category: "Milkshake Special", price: 100 },
  { id: 127, name: "Nutella Shake", category: "Milkshake Special", price: 120 },
  { id: 128, name: "Peanut Butter Shake", category: "Milkshake Special", price: 150 },
  { id: 129, name: "Red Velvet Cream Shake", category: "Milkshake Special", price: 120 },
  { id: 130, name: "Van & Choco", category: "Milkshake Special", price: 150 },
  // Toast
  { id: 131, name: "VEG ROLL", category: "Toast", price: 50 },
  { id: 132, name: "VEG CHEESE GRILL", category: "Toast", price: 70 },
  { id: 133, name: "CORN GRILL", category: "Toast", price: 70 },
  { id: 134, name: "SCHEZWAN VEG CHEESE GRILL", category: "Toast", price: 80 },
  { id: 135, name: "SCHEZWAN CORN CHEESE GRILL", category: "Toast", price: 80 },
  { id: 136, name: "CHILLI CHEESE GRILL", category: "Toast", price: 80 },
  { id: 137, name: "BUTTER GRILL", category: "Toast", price: 40 },
  { id: 138, name: "PANEER GRILL", category: "Toast", price: 70 },
  { id: 139, name: "PANEER CHEESE GRILL", category: "Toast", price: 85 },
  { id: 140, name: "ALOO CHEESE GRILL", category: "Toast", price: 70 },
  { id: 141, name: "JAM BUTTER GRILL", category: "Toast", price: 40 },
  { id: 142, name: "CHOCOLATE CHEESE GRILL", category: "Toast", price: 70 },
  { id: 143, name: "VEG MAYO GRILL", category: "Toast", price: 80 },

  // Sandwiches
  { id: 144, name: "VEG SANDWICH", category: "Sandwiches", price: 50 },
  { id: 145, name: "VEG MAYO SANDWICH", category: "Sandwiches", price: 60 },
  { id: 146, name: "ALOO BUJIA SANDWICH", category: "Sandwiches", price: 60 },
  { id: 147, name: "KHAKHRA SANDWICH", category: "Sandwiches", price: 80 },
  { id: 148, name: "KHAKHRA CHEESE SANDWICH", category: "Sandwiches", price: 90 },
  { id: 149, name: "MURUKKU SANDWICH", category: "Sandwiches", price: 70 },
  { id: 150, name: "MURUKKU CHEESE SANDWICH", category: "Sandwiches", price: 80 },

  // Burger
  { id: 151, name: "VEG BURGER", category: "Burger", price: 80 },
  { id: 152, name: "VEG CHEESE BURGER", category: "Burger", price: 100 },
  { id: 153, name: "PANEER BURGER", category: "Burger", price: 100 },
  { id: 154, name: "PANEER CHEESE BURGER", category: "Burger", price: 120 },
  // Icecream Shake
  { id: 155, name: "CHOCLATE", category: "Icecream Shake", price: 100 },
  { id: 156, name: "PISTACHIO", category: "Icecream Shake", price: 100 },
  { id: 157, name: "BUTTERSCOTCH", category: "Icecream Shake", price: 100 },
  { id: 158, name: "STRAWBERRY", category: "Icecream Shake", price: 100 },
  { id: 159, name: "MANGO", category: "Icecream Shake", price: 100 },
  { id: 160, name: "BLUEBERRY", category: "Icecream Shake", price: 100 },
  { id: 161, name: "BLACKCURRANT", category: "Icecream Shake", price: 100 },
  { id: 162, name: "VANILLA", category: "Icecream Shake", price: 100 },
  { id: 163, name: "FIG & HONEY", category: "Icecream Shake", price: 100 },
  { id: 164, name: "KULFI", category: "Icecream Shake", price: 100 },
  { id: 165, name: "SPANISH DELIGHT", category: "Icecream Shake", price: 120 },

  // Monster Shake's
  { id: 166, name: "NUTELLA MONSTER SHAKE", category: "Monster Shake's", price: 150 },
  { id: 167, name: "OREO MONSTER", category: "Monster Shake's", price: 150 },
  { id: 168, name: "CHOCO MONSTER", category: "Monster Shake's", price: 130 },
  { id: 169, name: "KIT KAT MONSTER", category: "Monster Shake's", price: 150 },

  // Cold Coffee
  { id: 170, name: "NORMAL COLD COFFEE", category: "Cold Coffee", price: 50 },
  { id: 171, name: "CARAMEL ICED COFFEE", category: "Cold Coffee", price: 100 },
  { id: 172, name: "NUTELLA COFFEE", category: "Cold Coffee", price: 120 },
  { id: 173, name: "PEANUT COFFEE", category: "Cold Coffee", price: 80 },
  { id: 174, name: "OREO COFFEE", category: "Cold Coffee", price: 100 },
  { id: 175, name: "KIT KAT COFFEE", category: "Cold Coffee", price: 100 },

  // Parcel (placed last)
  { id: 176, name: "CUP TEA", category: "Parcel", price: 15 },
  { id: 177, name: "CUP MILK", category: "Parcel", price: 15 },
  { id: 178, name: "SPECIAL CUP TEA", category: "Parcel", price: 15 },
  { id: 179, name: "CUP COFFEE", category: "Parcel", price: 20 },
  { id: 180, name: "RAGI MALT", category: "Parcel", price: 20 },
  { id: 181, name: "CHUKKU COFFEE", category: "Parcel", price: 20 },
  { id: 182, name: "BOOST", category: "Parcel", price: 20 },
  { id: 183, name: "HORLICKS", category: "Parcel", price: 20 }
];









  
  
    
